### ISSUE TITLE
It do not change the wall

### ISSUE THREAD

**Issue by Daniel-Ric** [tim03we/WallSystem-Nukkit#2]
Error message (when I click on the button to change):
java.lang.NullPointerException

at cn.nukkit.level.format.anvil.ChunkSection.getBlockLight(ChunkSection.java:193)

at cn.nukkit.level.format.anvil.Chunk.getBlockLight(Chunk.java:469)

at com.boydti.fawe.nukkit.optimization.queue.NukkitQueue.getEmmittedLight(NukkitQueue.java:342)

at com.boydti.fawe.nukkit.optimization.queue.NukkitQueue.getEmmittedLight(NukkitQueue.java:36)

at com.boydti.fawe.example.MappedFaweQueue.getEmmittedLight(MappedFaweQueue.java:630)

at com.boydti.fawe.example.NMSRelighter.computeSpreadBlockLight(NMSRelighter.java:266)

at com.boydti.fawe.example.NMSRelighter.updateBlockLight(NMSRelighter.java:235)

at com.boydti.fawe.example.NMSRelighter.fixBlockLighting(NMSRelighter.java:307)

at com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:296)

at com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:47)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

**Comment by tim03we** [comment]
I can not judge this error, because the plugin works fine for me.
